# Generated by Django 5.2.12 on 2026-03-23 19:24

import django.contrib.auth.models
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="last name")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "email",
                    models.EmailField(
                        help_text="Required. Enter a valid email address.",
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "email_verified",
                    models.BooleanField(default=False, help_text="Whether the user's email has been verified."),
                ),
                (
                    "email_verified_at",
                    models.DateTimeField(blank=True, help_text="Timestamp when email was verified.", null=True),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                    ),
                ),
                (
                    "failed_login_attempts",
                    models.PositiveIntegerField(default=0, help_text="Number of consecutive failed login attempts."),
                ),
                (
                    "locked_until",
                    models.DateTimeField(blank=True, help_text="Account locked until this timestamp.", null=True),
                ),
                (
                    "password_changed_at",
                    models.DateTimeField(auto_now_add=True, help_text="When password was last changed."),
                ),
                (
                    "two_factor_enabled",
                    models.BooleanField(
                        default=False, help_text="Whether TOTP two-factor authentication is active on this account."
                    ),
                ),
                (
                    "is_social_account",
                    models.BooleanField(
                        default=False,
                        help_text="True when the account was created via a social/OAuth2 provider. Social accounts may not have a usable password.",
                    ),
                ),
                (
                    "social_provider",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The social provider slug (e.g. 'google-oauth2', 'github'). Empty for password accounts.",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "date_of_birth",
                    models.DateField(blank=True, help_text="Required at registration for 16+ age gate.", null=True),
                ),
                (
                    "bio",
                    models.CharField(blank=True, help_text="Short bio shown on the public profile.", max_length=300),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Profile photo. Validated for size and content in Phase 2.",
                        null=True,
                        upload_to="avatars/",
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        help_text="Exact lat/lng stored on write; snapped to 500 m grid on read.",
                        null=True,
                        srid=4326,
                    ),
                ),
                (
                    "neighborhood",
                    models.CharField(
                        blank=True, help_text="Derived from reverse geocoding (Nominatim).", max_length=100
                    ),
                ),
                (
                    "preferred_genres",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        help_text="Up to 5 genre tags for discovery matching.",
                        size=5,
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(default="en", help_text="Preferred book language: en, nl, both.", max_length=20),
                ),
                (
                    "preferred_radius",
                    models.PositiveIntegerField(default=5000, help_text="Search radius in metres for nearby books."),
                ),
                (
                    "avg_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Computed average from swap partner ratings.",
                        max_digits=3,
                    ),
                ),
                ("swap_count", models.PositiveIntegerField(default=0, help_text="Total completed swaps.")),
                ("rating_count", models.PositiveIntegerField(default=0, help_text="Total ratings received.")),
                (
                    "coc_accepted_at",
                    models.DateTimeField(
                        blank=True, help_text="When the user accepted the Community Code of Conduct.", null=True
                    ),
                ),
                (
                    "coc_version",
                    models.CharField(blank=True, help_text="Version of the CoC the user accepted.", max_length=10),
                ),
                (
                    "auth_provider",
                    models.CharField(
                        blank=True, help_text="Simplified auth origin: 'email', 'google', or 'apple'.", max_length=20
                    ),
                ),
                (
                    "onboarding_completed",
                    models.BooleanField(
                        default=False, help_text="True after the user completes the location-setup onboarding."
                    ),
                ),
                (
                    "deletion_requested_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when user requests account deletion; cleared on cancellation. Accounts are anonymized 30 days after this timestamp.",
                        null=True,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "bookswap_user",
                "abstract": False,
                "swappable": "AUTH_USER_MODEL",
                "indexes": [
                    models.Index(fields=["email"], name="bookswap_us_email_00e892_idx"),
                    models.Index(fields=["username"], name="bookswap_us_usernam_a78398_idx"),
                    models.Index(fields=["email_verified"], name="bookswap_us_email_v_55386f_idx"),
                    models.Index(fields=["created_at"], name="bookswap_us_created_96a0ca_idx"),
                    models.Index(fields=["onboarding_completed"], name="bookswap_us_onboard_411ceb_idx"),
                    models.Index(fields=["location"], name="user_location_gist"),
                ],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
