# Generated by Django 5.2.12 on 2026-03-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, help_text='Set when user requests account deletion; cleared on cancellation. Accounts are anonymized 30 days after this timestamp.', null=True),
        ),
    ]
