# Generated by Django 5.2.12 on 2026-05-02 16:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookswap", "0002_user_profile_public"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="user_location_gist",
        ),
    ]
