# Generated by Django 5.2.11 on 2026-04-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_mobile_device"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("new_request", "New Partner Request"),
                    ("request_accepted", "Request Accepted"),
                    ("request_declined", "Request Declined"),
                    ("request_expired", "Request Expired"),
                    ("counter_proposed", "Counter Proposed"),
                    ("counter_approved", "Counter Approved"),
                    ("exchange_completed", "Exchange Completed"),
                    ("new_message", "New Message"),
                    ("rating_received", "Rating Received"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
