# Generated by Django 5.2.12 on 2026-04-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("new_request", "New Partner Request"),
                    ("request_accepted", "Request Accepted"),
                    ("request_declined", "Request Declined"),
                    ("request_expired", "Request Expired"),
                    ("request_cancelled", "Request Cancelled"),
                    ("counter_proposed", "Counter Proposed"),
                    ("counter_approved", "Counter Approved"),
                    ("swap_confirmed", "Swap Confirmed"),
                    ("exchange_completed", "Exchange Completed"),
                    ("return_requested", "Return Requested"),
                    ("exchange_returned", "Exchange Returned"),
                    ("new_message", "New Message"),
                    ("rating_received", "Rating Received"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
