# Generated by Django 5.2.12 on 2026-04-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exchanges", "0004_swap_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchangerequest",
            name="completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the exchange first entered a ratable state (completed/returned). Anchors the 30-day rating window.",
                null=True,
            ),
        ),
    ]
