# Generated by Codex on 2026-04-26

from django.db import migrations, models


def backfill_counter_counts(apps, schema_editor):
    ExchangeRequest = apps.get_model("exchanges", "ExchangeRequest")
    ExchangeRequest.objects.filter(last_counter_by_id=models.F("requester_id")).update(
        requester_counter_count=1,
    )
    ExchangeRequest.objects.filter(last_counter_by_id=models.F("owner_id")).update(
        owner_counter_count=1,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("exchanges", "0005_add_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchangerequest",
            name="owner_counter_count",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Number of counter-offers made by the owner.",
            ),
        ),
        migrations.AddField(
            model_name="exchangerequest",
            name="requester_counter_count",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Number of counter-offers made by the requester.",
            ),
        ),
        migrations.RunPython(backfill_counter_counts, migrations.RunPython.noop),
    ]
