# Generated by Django 5.2.11 on 2026-04-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_swap_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookphoto',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='book_thumbs/'),
        ),
    ]
